server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 116.62.148.11
                port: 5672
                username: guest
                password: guest
      bindings:
        input:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit
          group: cloud-stream-consumer

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone:  http://eureka1.com:7001/eureka/,http://eureka2.com:7002/eureka/
  instance:
    instance-id: stream-consumer8802
    prefer-ip-address: true
