server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.32.128:8848
    sentinel:
      transport:
        dashboard: 192.168.32.128:8858
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未占用的端口
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.32.128:8848
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

#开放所有路径用于图形化展示，默认只开放了info、health两个端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

#激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true