server:
  port: 8002

spring:
  application:
    name: cloud-prodiver-hystrix-payment
  zipkin:
    base-url: http://116.62.148.11:9411
  sleuth:
    sampler:
    probability: 1

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/,http://eureka2.com:7002/eureka
  instance:
    instance-id: payment8002
    prefer-ip-address: true