server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:  #设置需要绑定的rabbitmq的服务信息
       defaultRabbit: #表示定义的名称，用于bingding集合
        type: rabbit  #消息组件类型是RabbitMQ
        environment:  #设置RabbitMQ的环境变量
          spring:
            rabbitmq:
              host: 116.62.148.11
              port: 5672
              username: guest
              password: guest
      bindings:  #服务的整合处理
        input:  #这个名字是一个通道的名称
          destination: studyExchange  #表示要使用的Exchange名称
          content-type: application/json  #设置消息类型，本次为json，文本则设置“text/plain"
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          group: cloud-stream-consumer

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/,http://eureka2.com:7002/eureka/
  instance:
    instance-id: stream-consumer8802
    prefer-ip-address: true