server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.32.128:8848/
    alibaba:
      seata:
        # 自定义事务组名称需要与seata-server中的对应
        tx-service-group: my_test_tx_group
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据操作类型
    driver-class-name: org.gjt.mm.mysql.Driver  #mysql驱动包
    url: jdbc:mysql://116.62.148.11:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://116.62.148.11:3306/seata_order
    username: root
    password: abc123

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.cj.springcloud.alibaba.entities

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:           #服务名，填写default为所有服务
        connectTimeout: 1000
        readTimeout: 12000

logging:
  level:
    io:
      seata: info


#seata:
#  enabled: true
#  application-id: applicationName
#  tx-service-group: my_test_tx_group
#  enable-auto-data-source-proxy: true
#  config:
#    type: nacos
#    nacos:
#      serverAddr: 192.168.32.128:8848
#      group: SEATA_GROUP
#      namespace:
#      userName: "nacos"
#      password: "nacos"
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: 192.168.32.128:8848
#      namespace:
#      userName: "nacos"
#      password: "nacos"