server:
  port: 83

spring:
  application:
    name: nacos-payment-consumer
  cloud:
    nacos:
      discovery:
        server-addr: http://116.62.148.11:8848/

#消费者将要去访问的微服务名称
service-url:
  nacos-user-service: http://nacos-payment-provider
