server:
  port: 80

spring:
  application:
    name: cloud-payment-consumer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/,http://eureka2.com:7002/eureka
  instance:
    instance-id: consumer80
    prefer-ip-address: true

#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #建立连接所用的时间
  ConnectTimeout: 1000
  #建立连接后服务器响应时间
  ReadTimeout: 5000

logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.cj.springcloud.service.PaymentFeignService: debug
