server:
  port: 80

spring:
  application:
    name: cloud-payment-consumer
  zipkin:
    base-url: http://116.62.148.11:9411
    sleuth:
      sampler:
      #采样率介于0到1之间，1表示全部采集
      probability: 1

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/,http://eureka2.com:7002/eureka/
  instance:
    instance-id: consumer80
    prefer-ip-address: true

#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #建立连接所用的时间
  ConnectTimeout: 1000
  #建立连接后服务器响应时间
  ReadTimeout: 5000

logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.cj.springcloud.service.PaymentFeignHystrixService: debug

feign:
  hystrix:
    enabled: true
